-- INSERT DONNÉES TEST
-- À copier dans src/main/resources/sql/init-data.sql
-- Cette version s'exécute APRÈS la création des tables par Hibernate

-- CATÉGORIES
INSERT INTO CATEGORIE (NOM, DESCRIPTION, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Entrées', 'Plats pour commencer', NOW(), NOW());

INSERT INTO CATEGORIE (NOM, DESCRIPTION, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Plats Principaux', 'Viandes, poissons et pâtes', NOW(), NOW());

INSERT INTO CATEGORIE (NOM, DESCRIPTION, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Desserts', 'Desserts et friandises', NOW(), NOW());

INSERT INTO CATEGORIE (NOM, DESCRIPTION, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Boissons', 'Eau, sodas, vin', NOW(), NOW());

-- PLATS (les IDs des catégories seront 1,2,3,4)
INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Salade Cesar', 8.50, 'Salade fraîche avec parmesan', 1, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Soupe à l''oignon', 6.00, 'Soupe gratinée maison', 1, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Steak Frites', 15.99, 'Steak 200g avec frites croustillantes', 2, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Filet de poisson', 14.50, 'Filet du jour avec légumes', 2, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Pâtes Carbonara', 12.00, 'Pâtes sauce crème et bacon', 2, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Tiramisu', 6.50, 'Dessert italien classique', 3, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Crème Brûlée', 7.00, 'Crème vanille avec sucre caramélisé', 3, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Eau minérale', 2.50, 'Bouteille 50cl', 4, NULL, NULL, NOW(), NOW());

INSERT INTO PLAT (NOM, PRIX, DESCRIPTION, CATEGORIE_ID, IMAGE_BASE64, IMAGE_PATH, DATE_CREATION, DATE_MODIFICATION)
VALUES ('Vin rouge Bordeaux', 25.00, 'Verre de vin rouge local', 4, NULL, NULL, NOW(), NOW());

-- TABLES
INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (1, 2, FALSE, NOW(), NOW());

INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (2, 2, FALSE, NOW(), NOW());

INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (3, 4, FALSE, NOW(), NOW());

INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (4, 4, FALSE, NOW(), NOW());

INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (5, 6, FALSE, NOW(), NOW());

INSERT INTO TABLE_RESTO (NUMERO_TABLE, CAPACITE, OCCUPEE, DATE_CREATION, DATE_MODIFICATION)
VALUES (6, 6, FALSE, NOW(), NOW());